security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_UTILISATEUR:     ROLE_USER
        ROLE_ADMIN:       ROLE_ADMIN
        #ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:       
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                default_target_path: 
                always_use_default_target_path: false 
                use_referer: true 
                success_handler: redirect.after.login
            logout:  
                path: /logout
                target: /login
                success_handler: redirect.after.logout
            anonymous:    true
         
        public:
                    # since anonymous is allowed users will not be forced to login
             pattern:   ^/.*
             fos_facebook:
                  app_url: "http://apps.facebook.com/WeeGo/"
                  server_url: "http://localhost:80/"
             anonymous: true
        # defaut login area for standard users 

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }   
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/, role: ROLE_USER }